### ISSUE TITLE
Don't refresh Trace page when auto refresh is on

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking-ui#135]
Trace is too many, and people are not usually looking for the latest one, except for preview and demo. And if refresh the list every time, people will lose their trace timeline graph even they already open it.

And of source, you could show a tip at the top of the page to tell users that, this page will not refresh even you open the auto refresh.

**Comment by hanahmily** [comment]
I have refactor trace search page,  then the trace time line is present in another page. Fix in d4a0ee8c4955c06f924a139b09b7037a38beffee
