### ISSUE TITLE
Fail to render Dependency Map

### ISSUE THREAD

**Issue by hanahmily** [apache/incubator-skywalking-ui#141]
When `callsPerSec` or `avgResponseTime` is 0, the map is fail to render.

**Comment by wangmh** [comment]
我那最新版的试验了下，还存在类似的问题
{"data":{"getServiceResponseTimeTrend":{"trendList":[0,0,0,5,399,7,19,239,6,6,0,0,6,50,18,6]},"getServiceThroughputTrend":{"trendList":[0,0,0,1,1,1,1,1,1,1,0,0,1,1,1,1]},"getServiceSLATrend":{"trendList":[10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000]},"getServiceTopology":{"nodes":[{"id":"-3","name":"OrgRelationShipService.queryOrgRelationShipWithEmp","sla":10000,"calls":11,"numOfServiceAlarm":0},{"id":"-2","name":"Mysql/JDBI/PreparedStatement/execute","sla":10000,"calls":215,"numOfServiceAlarm":0},{"id":"3","name":"Mysql/JDBI/Connection/commit","sla":10000,"calls":212,"numOfServiceAlarm":0},{"id":"1","name":"User","type":"USER"}],"calls":[{"source":"-175","target":"-3","isAlert":false,"callType":"GRPC","cpm":0,"avgResponseTime":52},{"source":"1","target":"-3","isAlert":false,"callType":"GRPC","cpm":0,"avgResponseTime":145},{"source":"-106","target":"-3","isAlert":false,"callType":"GRPC","cpm":0,"avgResponseTime":6},{"source":"-3","target":"-2","isAlert":false,"callType":"GRPC","cpm":0,"avgResponseTime":60},{"source":"-3","target":"3","isAlert":false,"callType":"GRPC","cpm":0,"avgResponseTime":0}]}}}

**Comment by hanahmily** [comment]
This is another question. The "-175" is invalid node id. 
The UI project should valid data, and collector project needs to check the returned data
