### ISSUE TITLE
startTime There is no correct ordering

### ISSUE THREAD

**Issue by xjr100419** [apache/incubator-skywalking-ui#157]
![tim 20180418155007](https://user-images.githubusercontent.com/8691355/38918892-96ebce7e-4321-11e8-9130-eecf40401b29.png)
![tim 20180418155435](https://user-images.githubusercontent.com/8691355/38918898-9c7fc502-4321-11e8-9ebd-b1668ea84400.png)

1.startTime is not auto refresh now
but There is no correct ordering

2. it Trigger other exceptions
https://github.com/apache/incubator-skywalking-ui
i git the master branch and run
npm install
npm run build
npm run start:no-mock

**Comment by hanahmily** [comment]
@xjr100419 
1. The bug has fixed in https://github.com/apache/incubator-skywalking-ui/pull/156
2.  The master branch is unstable. This issue will be fixed in 5.0.0-beta or you can submit a pr to fix it.

**Comment by xjr100419** [comment]
ok ths
