### ISSUE TITLE
npm install of GUI yields bad shasum

### ISSUE THREAD

**Issue by gregpierro** [apache/incubator-skywalking-ui#164]
# npm install htmlparser2@~3.3.0
npm ERR! Linux 3.10.0-693.17.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "htmlparser2@~3.3.0"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-80992-194a38c1/registry.npmjs.org/htmlparser2/-/htmlparser2-3.3.0.tgz
npm ERR! Expected: cc70d05a59f6542e43f0e685c982e14c924a9efe
npm ERR! Actual:   1ab153cfa359ebf6bbc3000dcaf566ba5d5c3001
npm ERR! From:     https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.3.0.tgz

I searched far and wide nothing fixes, npm cache clean, removing package-lock.json, etc. Please help.

**Comment by wu-sheng** [comment]
I just run `npm install` and `npm start`, but I am success.

**Comment by gregpierro** [comment]
Hi. Thanks. I switched to a new machine internally and uses our artifactory mirror. i got a bit further. i did have one module install warning about husky. i still tried to npm install and npm start and nomock mode. and got the same error now as follows: 

./src/routes/Dashboard/Dashboard.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (native)

**Comment by gregpierro** [comment]
hi Sheng. I am trying to use this tool for APM/tracing of Java apps and microservices (Springboot). I'm not sure what is meant by Real SkyWalking collector. I followed this quickstart.
http://skywalking.apache.org/html/2017/12/20/quick-start.html 

i installed this collector (standalone with Elasticsearch) - https://github.com/apache/incubator-skywalking 
i installed this UI - https://github.com/apache/incubator-skywalking-ui#quickstart

My goal is simply to configure java agents and view the data through the UI. Should i be using mock mode or nomock mode?

**Comment by wu-sheng** [comment]
@gregpierro Oh, I have to say, I am sorry for you. I found out what is problem. This document page is out of date. Because the project moved all documents to here: https://github.com/apache/incubator-skywalking/blob/master/docs/README.md

And your quick-start is at here: https://github.com/apache/incubator-skywalking/blob/master/docs/en/Quick-start.md

I will give a brief, from 5.0.0-alpha release, the UI is integrated into collector in distribution. The UI project(this repo) is only for source management.

Sorry for misleading you so long time. I will update our official website.

**Comment by gregpierro** [comment]
ok no problem. so should i clone/download the master branch? Thank you!

**Comment by wu-sheng** [comment]
Document removed from our website. Sorry, again.

**Comment by wu-sheng** [comment]
> so should i clone/download the master branch?

Master branch is for developing only, please follow this document to build: https://github.com/apache/incubator-skywalking/blob/master/docs/en/How-to-build.md . It will guide you how to build from source.

And if only for use, please use the Apache release: http://skywalking.apache.org/downloads/
