### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by welinkiot** [apache/incubator-skywalking-ui#187]
./src/routes/Dashboard/Dashboard.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (native)

**Comment by CarterLi** [comment]
Remove `transform-decorators-legacy` in `.webpackrc.js`

Reference: ant-design/ant-design-pro#1345

**Comment by hanahmily** [comment]
I have build project with `npm install`, then `npm run build`. There's no error there.
