### ISSUE TITLE
remember select TimeRange 

### ISSUE THREAD

**Issue by liguobao** [apache/incubator-skywalking-ui#195]
if web refresh , TimeRange will reset to "Last 15 minutes".
But we expect the web remember last select.

**Comment by wu-sheng** [comment]
Don't refresh the browser, click `refresh` button. It works at my place.

![image](https://user-images.githubusercontent.com/5441976/45737581-d434b700-bc20-11e8-8b7f-ce9f12cfda23.png)

**Comment by liguobao** [comment]
but if  I  refresh the browser, the select lost.

I think the web should remember last select.

We can write select-value to cookie .
