### ISSUE TITLE
how to develop with it

### ISSUE THREAD

**Issue by coki230** [apache/incubator-skywalking-ui#209]
sorry, i am a java coder, so i am confused by how it work. 
could you prompt me how to add a page and how to get data from DB or ES.
or what type of knowledge should i learn. thank you.

**Comment by wu-sheng** [comment]
It doesn't get data from DB or ES, actually. This is the official SkyWalking query protocol for UI, https://github.com/apache/incubator-skywalking/blob/master/docs/en/protocols/README.md#query-protocol
