### ISSUE TITLE
list of servers in container (6.0.0-GA)

### ISSUE THREAD

**Issue by liudingnet** [apache/incubator-skywalking-ui#237]
2 oap servers cluster in docker container, when ui deployed in the host or VM, it could access the collector, but when ui deployed in the container, it can't access the collector.

**Comment by wu-sheng** [comment]
That is the basic network issue. You need to learn more about docker, that is all. Network accessible is not the goal of skywalking.

**Comment by liudingnet** [comment]
Container Deployed Cluster Architect.
I solved the problem, should upgrade the spring cloud to 2.x, otherwise ui zuul property named"list of servers" can be ignored with default value 127.0.0.1:12800. You could easily repeat it!

**Comment by wu-sheng** [comment]
I am not sure. My production environment is running in container and k8s based always. So, I am not sure the issue.
