### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by dengbin19910916** [apache/incubator-skywalking-ui#240]
./src/index.js
Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.

**Comment by wu-sheng** [comment]
I compiled successfully, just at yesterday.

**Comment by wu-sheng** [comment]
And notice this is new UI. https://github.com/apache/skywalking-rocketbot-ui

**Comment by dengbin19910916** [comment]
thank you
