### ISSUE TITLE
UI not functioning

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking-ui#87]
Hi , does 5.0-2018-preview UI merged all code from 3.2.6 yet? Seems many code from 3.2.6 is not moved to 5.0-2018-preview

**Comment by wu-sheng** [comment]
@zone1511 No, it won't. All UI codes are new, for the better visualization.

**Comment by zone1511** [comment]
Hi PMC,
  Any target date to implement the new UI? With out the UI, the agent cannot work itself. I tried use old UI to view the data and found that the transaction detail no longer able to display. It is because the underlying data format changed between 5.0 and 3.2.x?

**Comment by wu-sheng** [comment]
You can use the 3.2.6 tag of UI and SkyWalking to make things work. e.g. UI 3.2.6 , https://github.com/apache/incubator-skywalking-ui/tree/v3.2.6 

> It is because the underlying data format changed between 5.0 and 3.2.x

The answer is definitely **YES**. The network protocol and data stored in ES will/have been changed for new UI and new features.

>  Any target date to implement the new UI?

The expected releasing date is about Feb 2018, near Chinese new year, we hope.

**Comment by wu-sheng** [comment]
Nothing to update.
