### ISSUE TITLE
打不开ui界面

### ISSUE THREAD

**Issue by wolfelven** [apache/incubator-skywalking-ui#88]
根据quick-start，执行startup.sh后，打不开http://127.0.0.1:8080/这个页面，是为什么呢？是因为还缺少什么步骤吗？

**Comment by wu-sheng** [comment]
Please the releases or tag source codes. The master is the develop branch, it it not ready yet.

**Comment by wolfelven** [comment]
我用的是release v3.2.6的代码。用tar.gz和zip都试过，都是不行。

**Comment by wu-sheng** [comment]
If you have any issue, please post your logs to show us what is happening. There are many community users running the `3.2.6`. I assume you didn't install the skywalking right.
