### ISSUE TITLE
skywalking-ui can't open

### ISSUE THREAD

**Issue by wolfelven** [apache/incubator-skywalking-ui#89]
According to the README.md, I download https://github.com/apache/incubator-skywalking-ui/releases/v3.2.6. when I run startup.sh,the commond shows:
Starting web service....
Skywalking Web started successfully!
But I can't open http://127.0.0.1:8080/ in browser .

**Comment by wu-sheng** [comment]
You will find the log file in `/log` folder of UI.

**Comment by wolfelven** [comment]
sorry, my /logs is empty.
By the way, I only startup the web-ui, there is no skywalking-agent and collector.

**Comment by wu-sheng** [comment]
I think you should check you JRE(1.8 requirement). And you can try to run the commands(in .bat) line by line by yourself, in order to find what really happen. The output(`startup successfully`) likes Tomcat's startup, which only means the commend executed.

**Comment by wu-sheng** [comment]
Closing. No updates  in more than 7 days
