### ISSUE TITLE
unable to build the project under feature/5.0.0

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking-ui#92]
two errors occurs

1. Dashboard.java:[31,2] incompatible types: graphql.schema.GraphQLSchema cannot be converted to java.lang.annotation.Annotation
2. /CollectorUIServerGetterTimer.java:[70,38] cannot find symbol symbol:   method getServers() location: variable uiConfig of type org.apache.skywalking.apm.ui.config.UIConfig
for 2nd error, the getter is generated by lombok, just wonder why maven report it is not found. So as the IDE...

**Comment by wu-sheng** [comment]
I think the current status of UI project is working on nodejs related parts. You can run `npm install` and `npm start` in `src/main/frontend` folder to see the pages.

But I don't think you can use the current UI.

**Comment by hanahmily** [comment]
This branch is under development. Please use the latest release.
