### ISSUE TITLE
overview/getAlarmTrend

### ISSUE THREAD

**Issue by hanahmily** [apache/incubator-skywalking-ui#98]
Exception while fetching data (/getAlarmTrend) : Duration data error, step: MONTH, start: 20170200000000, end: 20180200000000

**Comment by peng-yongsheng** [comment]
H2 DAO's implementation is empty.

 #### INPUT
```
{
  getAlarmTrend(duration: {start: "2017-01", end: "2018-02", step: MONTH}) {
    numOfAlarmRate
  }
}
```

 #### OUTPUT
```
{
  "data": {
    "getAlarmTrend": {
      "numOfAlarmRate": [
        6666
      ]
    }
  }
}
```

**Comment by hanahmily** [comment]
The result of test is the same as above.

**Comment by hanahmily** [comment]
Transfer to https://github.com/apache/incubator-skywalking/issues/855
